// Package healthz provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package healthz

// Dependency defines model for Dependency.
type Dependency struct {
	Name   string `json:"name"`
	Reason string `json:"reason"`
	Status string `json:"status"`
}

// Status defines model for Status.
type Status struct {
	Dependencies []Dependency `json:"dependencies"`
	Status       string       `json:"status"`
}
